[listener]
    [listener.mongodb]
    enabled = true
    incoming_port = 28017
    incoming_max_connection = 10
    idle_connection_seconds = 30
    ignore_meta_query = true

    [listener.log4j2Socket]
    enabled = true
    incoming_port = 28018
    incoming_max_connection = 10
    idle_connection_seconds = 30

    [listener.jsonSocket]
    enabled = true
    incoming_port = 28019
    incoming_max_connection = 10
    idle_connection_seconds = 30

    [listener.kafka]
    enabled = true
    address = "172.28.152.102:30092"
    topic = "anlink"

[backend]
    [backend.mongodb]
    url = "tech-tst-mongo.zhonganinfo.com:27017"

[og]
enabled = true
url="http://localhost:8000/new_archive"
#url="http://nbstock:30025/new_archive"
#url="http://172.28.152.106:30100/new_archive"
idle_connection_seconds = 5
buffer_size = 100
retry_times = 5

    [og.wsclient]
    enabled = true
    url="ws://localhost:8002/ws"

[audit]
    [audit.mongodb]
    uri = "mongodb://tech-tst-mongo.zhonganinfo.com:27017"
    username = "tech_udpp_backend_tst"
    password = ""
    database = "tech_udpp_backend"
    collection = "queryblockdb"
#    auth_method = "SCRAM-SHA-256"
