[log]
    level = "trace"

[listener]
    [listener.http]
    enabled = true
    port = 8080
    max_content_length = 10000000

[blockchain]
    [blockchain.og]
    enabled = true
    url="http://nbstock.top:30022/new_archive"
    idle_connection_seconds = 5
    buffer_size = 100
    retry_times = 5

