[log]
    level = "trace"

[listener]
    [listener.http]
    enabled = true
    port = 8080
    max_content_length = 10000000
    timeout_db_ms = 60000

[storage]
    [storage.mongodb]
    timeout_connect_ms = 15000

#    url = "mongodb://nbstock.top:30003"
#    database = "blockdb"
#    auth_method = "SCRAM-SHA-256"
#    username = "rw"
#    password = "comecome"


    url = "mongodb://localhost:27017"
    database = "blockdb"
    auth_method = ""
    username = "rw"
    password = "comecome"


[blockchain]
    [blockchain.og]
    enabled = true
    url="http://nbstock.top:30010/new_archive"
    idle_connection_seconds = 5
    buffer_size = 100
    retry_times = 5

        [blockchain.og.wsclient]
        enabled = true
        url="ws://nbstock.top:30012/ws"