[listener]
    [listener.mongodb]
    enabled = false
    incoming_port = 28017
    incoming_max_connection = 10
    idle_connection_seconds = 30
    ignore_meta_query = true

    [listener.log4j2Socket]
    enabled = false
    incoming_port = 28018
    incoming_max_connection = 10
    idle_connection_seconds = 30

    [listener.jsonSocket]
    enabled = false
    incoming_port = 28019
    incoming_max_connection = 10
    idle_connection_seconds = 30

    [listener.kafka]
    enabled = false
    address = "10.253.11.192:9092"
    topic = "tech-tech-anlink-web-gateway-201907101551"

    [listener.http]
    enabled = true
    port = 8080
    enable_audit = true
    enable_health = true
    max_content_length = 10000000

[backend]
    [backend.mongodb]
    # see http://mongodb.github.io/mongo-java-driver/3.6/javadoc/?com/mongodb/ConnectionString.html for full connection parameters
    connection_string = "mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database.collection][?options]]"
    url = "172.28.152.101:27017"

[og]
enabled = true
# url="http://172.28.152.101:8000/new_archive"
url="http://127.0.0.1:8000/new_archive"
idle_connection_seconds = 5
buffer_size = 100
retry_times = 3

    [og.wsclient]
    enabled = false
    url="ws://172.28.152.106:30102/ws"

[audit]
    [audit.mongodb]
    connection_string = "mongodb://@172.28.152.101:30052"
    database = "blockDB"
    collection = "queryblockdb"
[debug]
    enabled = false
    port = 8091

[log]
    level = "trace"